language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
before_install:
  - mkdir -p $HOME/.m2
  - cp example/settings-bintray.xml $HOME/.m2/settings.xml
install:
  - mvn install -DskipTests=true -B -V
before_deploy:
  - curl -s https://raw.githubusercontent.com/realglobe-Inc/travis-deploy-scripts/master/maven-generate-bintray-descriptor.sh | sh
deploy:
  provider: bintray
  file: bintray.json
  user: realglobe
  key:
    secure: w2pHD3u57sM57RW/wKNXNfh+7CzG945YWxrTkOUUzJ7h3/zRFLUOADg9YV6QmxMnWqVsEh/Z9R583k7rGMNSqIur8SY8mwA3WG8gAVqy71HxBGt0I/pAWCeffqWykNLXy5k/I1nStDJ8FBWcUHD3plohSY0rtL3quC35kbtD5NxX34kYp1ccurZTBltXDfex6Qf5FGY447x8Pt54RBPfPATJ7l4SKGNVk0y4zHiMABCXzzTSVAL+SHfvBRsSlPpkiht7n8xRD+3AnMf+HQIIsQ+8Cy4+I8jMd1puBxEM192WJOZljQQUiL93nKRuSaGSlIqGRv8NpIvjYfXBo5K74Vfqo8RTYSGELtQwiwZqdTy48CsKg/445F3afE9tLPpb8ABRKBK0XkKvrRFAjeMaD46KlcDR7guxCYAVTa4XJ3DpdxqSVmuIm1t+uVHBTCGFcnKjYLPt1uxZa7AdgHZqW5q30maUHhkCo4FXRbhLhWcPjo+nQ7SADM+G7yiDMs6iGPGfVZrNmuPI8DnKqeCEQ6stXNSb6PxnML+F6aqw2EMBmHfXi09Aa/CzO81oDbNu9gMe3t9tfIu/SI1gsCMLDATyPaSC7IGNYJL3fO/mgMJLdBYKoZfHHJr14oinHt4h+uHJ5Ihd8bD5M/Xdn0t6N7nXK8PaBQ9mOYfj6aVOYLE=
after_deploy:
  - curl -s https://raw.githubusercontent.com/realglobe-Inc/travis-deploy-scripts/master/maven-deploy-javadoc.sh | sh
